export enum WebviewEvent {
  OPEN_SETTING = "OPEN_SETTING",
  GET_ALARM_STATUS = "GET_ALARM_STATUS",
  OPEN_SERVICE_INTRODUCTION = "OPEN_SERVICE_INTRODUCTION",
  GET_DEVICE_TOKEN = "GET_DEVICE_TOKEN",
  REGISTER_DEVICE_TOKEN = "REGISTER_DEVICE_TOKEN",
}
